name: build and unittest
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    container:
      image: schnitzeltony/fedora-qt5:32
    steps:
      - uses: actions/checkout@master
      - name: install deps
        run: |
          sudo dnf -y install xorg-x11-server-Xvfb
      - name: Build
        run: |
          echo $HOME
          echo $GITHUB_WORKSPACE
          cd $HOME
          mkdir -p "$HOME/targetbuild"
          cd "$HOME/targetbuild"

          qmake-qt4 -query
          qmake-qt4 $GITHUB_WORKSPACE/wm-project.pro

          make -j $(getconf _NPROCESSORS_ONLN)
      - name: Unittests
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          cd "$HOME/targetbuild"
          make check
